### PR TITLE
pin rspec-core to version that works w/ruby 1.8.7

### PR DESCRIPTION
**Pull request by igalic**
this fix is analogous to
https://github.com/puppetlabs/puppetlabs-puppetdb/pull/167

### CODE REVIEW

**Comment by igalic** [comment]
cool! and now we're hitting https://github.com/rodjek/rspec-puppet/issues/227

**Comment by igalic** [comment]
@attachmentgenie fixed their tests for ufw, which were failing for similar reasons, here: https://github.com/attachmentgenie/attachmentgenie-ufw/commit/4fc3c6262f724939296c3ab60f3e0b10d77bb7a1

**Comment by igalic** [comment]
finally…ish…maybe…

**Comment by igalic** [comment]
@mbrodala ^ it's done. sorry took so long ~_~

**Comment by mbrodala** [comment]
No worries. Guess you're happy if Ruby 1.8.7 dies. ;-)

**Comment by igalic** [comment]
so, so, so very happy…

when all of software dies.

**Pull request merged**
