### PR TITLE
Add composer::repository type

### PR DESCRIPTION
**Pull request by mbrodala**
This type allows for managing composer repositories either locally in
project directories or globally.

### CODE REVIEW

**Comment by mbrodala** [comment]
Notice that this new type currently duplicates some code from `composer::project`. This needs some refactoring after merging this.

**Comment by mbrodala** [comment]
@igalic Could you have a look at the Ruby 1.8.7 build failures?

**Comment by igalic** [comment]
i have no idea how rspec or ruby works sometimes https://github.com/Brainsware/puppet-composer/pull/17

**Comment by mbrodala** [comment]
How to proceed here? The failing tests are not triggered by this change after all.

**Comment by igalic** [comment]
you're right! let's get this merged, and fix the tests separately

**Comment by mbrodala** [comment]
Thanks. :-) Next thing is refactoring of the environment bits.

**Comment by igalic** [comment]
yes!

**Pull request merged**
