### PR TITLE
prepare 0.3.2 release

### PR DESCRIPTION
**Pull request by igalic**
this time, we believe the .travis.yml to be *correct*

### CODE REVIEW

**Comment by mbrodala** [comment]
Thanks a lot. :-)

**Comment by mbrodala** [comment]
@igalic It seems like this release is not yet on Puppet Forge. I guess this only takes a little time?

**Comment by igalic** [comment]
@mbrodala nope, something is still wrong with our [`.travis.yml`](https://github.com/Brainsware/puppet-composer/blob/e65cc7c325dd01a5f81f6699960e4b1723a3c6ad/.travis.yml) as you can see in [travis](https://travis-ci.org/Brainsware/puppet-composer/requests) decided this isn't worth a deploy

**Comment by igalic** [comment]
btw, now, in theory, anyone with push access to this repository can make a release.
All they have to do is run `bundle exec rake release_checks` and `bundle exec rake travis_release`

**Pull request merged**
